targets:
  $default:
    sources:
      exclude: ["test/**"]
    builders:
      generator|generator:
        enabled: false

builders:
  generator:
    import: "package:generator/src/builders/parser_builder.dart"
    builder_factories: ["parserBuilder"]
    build_extensions: {".dart": [".parser.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|library_builder"]
