targets:
  $default:
    builders:
      built_value|built_value:
        enabled: true
      generator|generator:
        enabled: false

builders:
  generator:
    import: "package:generator/builder.dart"
    builder_factories: ["parseMethodBuilder"]
    build_extensions: {".dart": [".method.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
