targets:
  $default:
    sources:
      exclude: ["test/**"]
    builders:
      built_value_generator:built_value :
        enabled: true
      generator|generator:
        enabled: false

builders:
  generator:
    import: "package:generator/builder.dart"
    builder_factories: ["parseMethodBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|library_builder"]
