targets:
  $default:
    builders:
      built_value|built_value:
        enabled: true
      parse_gen|parse_gen:
        enabled: false

builders:
  parse_gen:
    import: "package:parse_gen/builder.dart"
    builder_factories: ["parseMethodBuilder"]
    build_extensions: {".dart": [".method.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
